#!/bin/sh

CONFIG_FILE='/etc/cft/cft.conf'

if [ "${1}" = '--config' -o "${1}" = '-c' ]; then
  CONFIG_FILE="${2}"
  [ "${CONFIG_FILE#/}" = "${CONFIG_FILE}" ] && CONFIG_FILE="/etc/cft/${CONFIG_FILE}"
  [ -e "${CONFIG_FILE}" ] || CONFIG_FILE="${CONFIG_FILE%.conf}.conf"
  shift 2
fi

FILE="${1}"

if [ -z "${FILE}" ]; then
	echo "USAGE: ${0##*/} <file>"
	exit
fi

source "${CONFIG_FILE}" || exit 1

if [ ! -e "${FILE}" ]; then
	echo "Local file ${FILE} not found"
	exit 1
fi

if [ ! -f "${FILE}" ]; then
	echo "Local file ${FILE} is not a regular file"
	exit 1
fi

TEMP_FILE=$(mktemp tmp.XXXX) || exit 1

rsync ${CFT_RSYNC_OPTS} -q \
    -e "ssh -p ${CFT_PORT:-22} ${CFT_SSH_OPTS}" \
    "${CFT_HOST}":"${CFT_ROOT}${CFT_ROOT:+/}${FILE}" "${TEMP_FILE}"

diff -u "${FILE}" "${TEMP_FILE}" |tail -n +3

rm "${TEMP_FILE}"
