#!/bin/sh

CONFIG_FILE=/etc/cft/cft.conf
PROG_NAME="${0##*/}"
COLOR='--color=always'

function print_usage() {
	echo "USAGE: ${PROG_NAME} [-c <conf_file>] [-r] <file>"
  echo "     -c --config <conf_file>    Use config <conf_file> instead of default (${CONFIG_FILE})"
  echo '     -r --reverse               Show diff in reverse'
  echo '     -C --no-color              Show diff without colors'
  echo '     -h --help                  Print this help'
  exit ${1}
}

while [ -n "${1}" ]; do
  case "${1}" in
    -c|--config)
      CONFIG_FILE="${2}"
      [ "${CONFIG_FILE#/}" = "${CONFIG_FILE}" ] && CONFIG_FILE="/etc/cft/${CONFIG_FILE}"
      [ -e "${CONFIG_FILE}" ] || CONFIG_FILE="${CONFIG_FILE%.conf}.conf"
      shift
      ;;
    -r|--reverse)
      REVERSE=yes
      ;;
    -C|--no-color)
      COLOR=
      ;;
    -h|--help)
      print_usage
      ;;
    *)
      if [ -z ${FILE} ]; then
        FILE="${1}"
      else
        print_usage
        echo "Unknown option ${1}" >&2
        exit 1
      fi
      ;;
  esac
  shift
done

[ -z "${FILE}" ] && print_usage 1

source "${CONFIG_FILE}" || exit 1

if [ ! -e "${FILE}" ]; then
	echo "Local file ${FILE} not found" >&2
	exit 1
fi

if [ ! -f "${FILE}" ]; then
	echo "Local file ${FILE} is not a regular file" >&2
	exit 1
fi

TEMP_FILE=$(mktemp tmp.XXXX) || exit 1

rsync ${CFT_RSYNC_OPTS} -q \
    -e "ssh -p ${CFT_PORT:-22} ${CFT_SSH_OPTS}" \
    "${CFT_HOST}":"${CFT_ROOT}${CFT_ROOT:+/}${FILE}" "${TEMP_FILE}"

if [ "${REVERSE}" = yes ]; then
  diff ${COLOR} -u "${TEMP_FILE}" "${FILE}" |tail -n +3
else
  diff ${COLOR} -u "${FILE}" "${TEMP_FILE}" |tail -n +3
fi

rm "${TEMP_FILE}"
