#!/bin/sh

CONFIG_FILE='/etc/cft/cft.conf'

if [ "${1}" = '--config' -o "${1}" = '-c' ]; then
  CONFIG_FILE="${2}"
  [ "${CONFIG_FILE#/}" = "${CONFIG_FILE}" ] && CONFIG_FILE="/etc/cft/${CONFIG_FILE}"
  [ -e "${CONFIG_FILE}" ] || CONFIG_FILE="${CONFIG_FILE%.conf}.conf"
  shift 2
fi

FILE="${1}"

if [ -z "${FILE}" ]; then
	echo "USAGE: ${0##*/} <file>"
	exit
fi

source "${CONFIG_FILE}" || exit 1

if [ ! -e "${FILE}" ]; then
	echo "Local file ${FILE} not found"
	exit 1
fi

if [ ! -f "${FILE}" ]; then
	echo "Local file ${FILE} is not a regular file"
	exit 1
fi

ssh ${CFT_SSH_OPTS} -p "${CFT_PORT}" "${CFT_HOST}" cat "${CFT_ROOT}${CFT_ROOT:+/}${FILE}" | diff -u "${FILE}" - |tail -n +3

