#!/bin/sh

CONFIG_FILE='/etc/cft/cft.conf'

if [ "${1}" = '--config' -o "${1}" = '-c' ]; then
  CONFIG_FILE="${2}"
  [ "${CONFIG_FILE#/}" = "${CONFIG_FILE}" ] && CONFIG_FILE="/etc/cft/${CONFIG_FILE}"
  [ -e "${CONFIG_FILE}" ] || CONFIG_FILE="${CONFIG_FILE%.conf}.conf"
  shift 2
fi

if [ "${1}" = '-i' ]; then
	INPLACE=yes
	shift
fi

if [ -z "${*}" -o "${1}" = "--help" ]; then
	echo "USAGE: ${0##*/} [-i] <file1> [file2] ..."
	echo '-i   inplace copy'
	exit
fi

source "${CONFIG_FILE}" || exit 1

for FILE in "${@}"; do
  [ "${INPLACE}" = 'yes' ] && DEST="${FILE}" || DEST='./'
  scp ${CFT_SSH_OPTS} -p -P "${CFT_PORT}" "${CFT_HOST}":"${CFT_ROOT}${CFT_ROOT:+/}${FILE}" "${DEST}" || exit 1
done
